sprint-2/step-2 перетаскивания, табы и всесоюзный стейт
ciberstrigo/react-burger pull request #4
Opened 2023-08-19 09:12 UTC by ciberstrigo

Не отрицаю что могут быть косяки, но я спешу. Времени на выходных практически нет, во вторник важное собеседование, а самостоятельное изучение тем в тренажёре заняло слишком много времени.

2023-08-19 10:21 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется redux;
- Реализован DnD;

### **Но есть несколько замечаний, которые нужно исправить:**

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/O-A0pBAPSoEkZA>;

- со временем приложение будет разрастаться, появится новый функционал, если все будет в одном редьюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

  - загрузка данных ингредиентов
  - отправка заказа
  - работа конструктора
  - открытие модального окна ингредиента

  Для объединения редьюсеров используйте combineReducers
  <https://redux.js.org/api/combinereducers>

- Если значения нет, то нужно использовать null, а не пустой объект.

- Следует разделить экшены по файлам, на нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если при

  В текущем приложении можно разделить на следующие файлы:

  - загрузка данных ингредиентов
  - работа конструктора
  - открытие ингредиента в попапе
  - оформление заказа

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-08-19 10:21 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.js
> +        .filter(item => {return item && item.type === 'bun'});
**Можно лучше:**

Тут у вас дублируется немного, лучше сделать так:

```js
const data= useSelector(store => store.burger.constructorIngredients);

const { bun, ingredients } = useMemo(() => {
  return {
    bun: data.find(item => item.type === 'bun'),
    ingredients: data.filter(item => item.type !== 'bun'),
  };
}, [data]);
```

2023-08-19 10:21 UTC, ArslanMustafin commented on src/services/actions/index.js
> +            })
**Можно лучше:**

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```js
const checkResponse = res => {
  return res.ok ? res.json() : res.json().then(err => Promise.reject(err));
};
```

`fetch(someUrl).then(checkResponse)`

**Можно лучше:**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```js
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}
```

и разместить их в отдельном файле `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-08-19 10:21 UTC, ArslanMustafin commented on src/services/actions/index.js
> +            "ingredients": ingredients.map(item => item._id)
**Можно лучше:**

Сюда лучше сразу передавать готовый массив id ингредиентов.

т.е. собираем массив в момент в обработчике событий `onClick` у кнопки `Оформить заказ`

```js
[bun._id, ...ingredients.map(item => item._id), bun._id];
```

2023-08-19 10:21 UTC, ArslanMustafin commented on src/services/reducers/index.js
> +    currentIngredient: {},
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-08-19 10:21 UTC, ArslanMustafin commented on src/services/reducers/index.js
> +    constructorIngredients: [],
**Можно лучше:**

тут лучше сделать разделение на булку и ингредиенты, так намного легче будет оперировать с данными.

2023-08-19 12:09 UTC, ciberstrigo commented on src/services/actions/index.js
> +            })
@ArslanMustafin не понимаю как вынести функции в отдельный файл. Что они должны возвращать? И где в итоге должен диспатчиться action?

2023-08-20 09:52 UTC, ArslanMustafin commented on src/services/actions/index.js
> +            })
В примере показано как, функции должна возвращать промис, а в экшене вы уже работаете с результатом промиса через then/catch.

2023-08-20 17:42 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Работа отклонена от проверки (без потери итерации), т.к. не были исправлены замечания которые описаны в общем замечании. Продублирую их тут.

## Замечания, которые нужно исправить

- `ingredients.length > 2 - BurgerConstructor` - это условие тут излишне. Главное чтобы были булки, ингредиенты необязательны.

- со временем приложение будет разрастаться, появится новый функционал, если все будет в одном редьюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

  - загрузка данных ингредиентов
  - отправка заказа
  - работа конструктора
  - открытие модального окна ингредиента

  Для объединения редьюсеров используйте combineReducers
  <https://redux.js.org/api/combinereducers>

- Следует разделить экшены по файлам, на нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если при

  В текущем приложении можно разделить на следующие файлы:

  - загрузка данных ингредиентов
  - работа конструктора
  - открытие ингредиента в попапе
  - оформление заказа

2023-08-20 17:42 UTC, ArslanMustafin commented on src/components/BurgerConstructor/BurgerConstructor.js
> +                            if (burgerBun && ingredients.length > 2) {
**Надо исправить:**

`ingredients.length > 2` - это условие тут излишне. Главное чтобы были булки, ингредиенты необязательны.

2023-08-21 17:05 UTC, ArslanMustafin commented
> Не отрицаю что могут быть косяки, но я спешу. Времени на выходных практически нет, во вторник важное собеседование, а самостоятельное изучение тем в тренажёре заняло слишком много времени. **UPD** Бро прошу пропусти. Времени ноль осталось, критические и пару "можно лучше" поправил. **UPD 2 ** редусеры и экшны разделил не мелкие.

Здравствуйте, я всё понимаю, но разделение редьюсера было требование чек-листа, без этого просто никак нельзя работу принимать)) Плюс у  вас вроде бы сломался drag-and-drop, но он работал сначала, поэтому войду в положение и приму работу, ток вы почините)) а то след ревьюер увидит и не оч приятная история получиться)

2023-08-21 17:05 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшей обучении!**

- Все замечания были исправлены;

2023-08-30 09:22 UTC, merged